name: Run frontend tests

on:
  push:
  # workflow_dispatch:
  # pull_request:
  #   branches:
  #     - master

# Main reference: https://ovirium.com/blog/how-to-make-mysql-work-in-your-github-actions/

jobs:
  test-host:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DB_DATABASE: testdb
      DB_USER: root
      DB_PASSWORD: root
      # apparently I could not change this password
      # if process.env.GITHUB_ACTIONS is 'true', the password at db.config.js will change to 'root'

    steps:
    - uses: actions/checkout@v2

    - name: Set up MySQL
      run: |
        echo $GITHUB_ACTIONS
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version

    - run: yarn test sample
    - run: yarn test selenium
      if: always()
    - run: yarn start &
      if: always()
    - run: yarn test frontpage
      if: always()
    # - run: yarn test campaign
    #   if: always()
    # - run: yarn test junctionTable
    #   if: always()
    # - run: yarn test recommender
    #   if: always()
    # - run: yarn test auth
    #   if: always()
    # - run: yarn test
    #   if: always()