name: Run frontend tests

on:
  push:
  # workflow_dispatch:
  # pull_request:
  #   branches:
  #     - master

# Main reference: https://ovirium.com/blog/how-to-make-mysql-work-in-your-github-actions/

jobs:
  test-host:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DB_DATABASE: testdb
      DB_USER: root
      DB_PASSWORD: root
      # apparently I could not change this password
      # if process.env.GITHUB_ACTIONS is 'true', the password at db.config.js will change to 'root'

    steps:
    - uses: actions/checkout@v2



    - uses: nanasess/setup-chromedriver@master
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '88.0.4324.96'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      
      
    - name: Set up MySQL
      run: |
        echo $GITHUB_ACTIONS
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test sample
    - run: yarn test selenium
    - run: yarn serve
    - run: yarn test frontpage
    # - run: yarn test campaign
    #   if: always()
    # - run: yarn test junctionTable
    #   if: always()
    # - run: yarn test recommender
    #   if: always()
    # - run: yarn test auth
    #   if: always()
    # - run: yarn test
    #   if: always()